### ISSUE TITLE
Creating a menu

### ISSUE THREAD

**Issue by twatkinz** [twatkinz/python-exercise#1]
**User Story**
As a new user, I want to know what options this program provides so that I can quit the program.

**Persona**
New users

**Feature**
Shows the options this program provides

**Business Value**
Allows the user to quit the program

**Task List**

- [ ] Code for outputting the menu
- [ ] Code for checking the user's input
- [ ] Code that shows the message again if user input is invalid

**Acceptance Criteria**

- This program can be run without crashing under the EC2 terminal with Python 3.10.
- The user can enter any key.

**Acceptance Tests**

- Run the program with 'q' as input, program should quit
- Run the program with invalid input, menu should come up again
